# Generated by Django 3.1.2 on 2020-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0019_add_decimal_places_to_percentage_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status"], name="djstripe_in_status_579158_idx"
            ),
        ),
    ]
