# Generated by Django 3.1 on 2021-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0019_add_decimal_places_to_percentage_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={},
        ),
        migrations.RemoveField(
            model_name="countryspec",
            name="djstripe_owner_account",
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="djstripe_in_status_579158_idx"),
        ),
    ]
