# Generated by Django 3.1 on 2021-02-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0020_add_index_on_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="metadata",
        )
    ]
