# Generated by Django 3.1 on 2021-02-23 15:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0020_invoice_add_index_on_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Invoice",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text="A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.",
                null=True,
            ),
        )
    ]
