# Generated by Django 3.1 on 2021-02-24 09:51

from django.db import migrations, models

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0021_invoice_remove_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="djstripe_invoice_status_4d27deb1_idx",
        ),
        migrations.AddField(
            model_name="invoice",
            name="metadata",
            field=djstripe.fields.JSONField(
                blank=True,
                help_text="A set of key/value pairs that you can attach to an object. It can be useful for storing additional information about an object in a structured format.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="djstripe_in_status_579158_idx"),
        ),
    ]
