# Generated by Django 3.1 on 2021-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0021_invoice_alert_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='djstripe_invoice_status_4d27deb1_idx',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='djstripe_in_status_579158_idx'),
        ),
    ]
