# Generated by Django 3.1.2 on 2021-04-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0021_invoice_add_new_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="metadata",
        )
    ]
