# Generated by Django 3.1.2 on 2021-04-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0022_invoice_remove_metadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="new_metadata",
            new_name="metadata",
        ),
    ]
